# Generated by Django 4.2 on 2024-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="body",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
